from __future__ import annotations
import os
import math
from datetime import datetime
from typing import Any, Dict

try:
    from fpdf import FPDF
    _HAVE_FPDF = True
except ImportError:
    _HAVE_FPDF = False

# ---- Brand palette -------------------------------------------------------
NAVY = (15, 23, 42)
NAVY_2 = (30, 41, 59)
BLUE = (37, 99, 235)
CYAN = (6, 182, 212)
INK = (17, 24, 39)
MUTE = (107, 114, 128)
LINE = (226, 232, 240)
CARD = (248, 250, 252)
GREEN = (22, 163, 74)
AMBER = (217, 145, 6)
RED = (220, 38, 38)
WHITE = (255, 255, 255)

BAND_COLOURS = {"green": GREEN, "amber": AMBER, "red": RED}
CLASS_LABELS = {
    "Normal": "Normal",
    "Cataract": "Cataract",
    "Glaucoma": "Glaucoma",
    "Diabetic_Retinopathy": "Diabetic Retinopathy",
}

PAGE_W = 210.0
MARGIN = 16.0
CONTENT_W = PAGE_W - 2 * MARGIN


class _Report(FPDF):
    def header(self):
        self.set_fill_color(*NAVY)
        self.rect(0, 0, PAGE_W, 30, style="F")
        self.set_fill_color(*BLUE)
        self.rect(0, 30, PAGE_W / 2, 1.4, style="F")
        self.set_fill_color(*CYAN)
        self.rect(PAGE_W / 2, 30, PAGE_W / 2, 1.4, style="F")
        self._eye_mark(MARGIN, 9.5, 12.5)
        self.set_xy(MARGIN + 16, 8.5)
        self.set_text_color(*WHITE)
        self.set_font("Helvetica", "B", 17)
        self.cell(80, 8, "SMART EYE", ln=0)
        self.set_xy(MARGIN + 16, 16.5)
        self.set_text_color(150, 197, 245)
        self.set_font("Helvetica", "", 7.5)
        self.cell(80, 5, "CLINICAL INTELLIGENCE", ln=0)
        self.set_xy(PAGE_W - MARGIN - 80, 10.5)
        self.set_text_color(*WHITE)
        self.set_font("Helvetica", "B", 12)
        self.cell(80, 6, "Ocular Health Report", align="R", ln=1)
        self.set_xy(PAGE_W - MARGIN - 80, 17.5)
        self.set_text_color(150, 197, 245)
        self.set_font("Helvetica", "", 8)
        self.cell(80, 5, "Preliminary screening - not a diagnosis", align="R", ln=1)
        self.set_y(40)

    def footer(self):
        self.set_y(-13)
        self.set_draw_color(*LINE)
        self.set_line_width(0.2)
        self.line(MARGIN, self.get_y(), PAGE_W - MARGIN, self.get_y())
        self.set_y(-11)
        self.set_font("Helvetica", "", 7.5)
        self.set_text_color(*MUTE)
        self.cell(0, 6, "Generated by Smart Eye  -  Screening support only  -  Not a clinical diagnosis", align="L")
        self.set_y(-11)
        self.cell(0, 6, f"Page {self.page_no()}", align="R")

    def _eye_mark(self, x, y, size):
        self.set_fill_color(*BLUE)
        self.rect(x, y, size, size, style="F", round_corners=True, corner_radius=2.5)
        cx, cy = x + size / 2, y + size / 2
        self.set_fill_color(*WHITE)
        self.ellipse(x + size * 0.16, y + size * 0.30, size * 0.68, size * 0.40, style="F")
        self.set_fill_color(*NAVY)
        self.ellipse(cx - size * 0.13, cy - size * 0.13, size * 0.26, size * 0.26, style="F")
        self.set_fill_color(*WHITE)
        self.ellipse(cx - size * 0.02, cy - size * 0.08, size * 0.06, size * 0.06, style="F")


def _section_title(pdf, text):
    y = pdf.get_y()
    pdf.set_fill_color(*BLUE)
    pdf.rect(MARGIN, y + 0.5, 2.5, 5.5, style="F")
    pdf.set_xy(MARGIN + 5, y)
    pdf.set_font("Helvetica", "B", 11.5)
    pdf.set_text_color(*INK)
    pdf.cell(0, 6.5, text, ln=1)
    pdf.ln(1.5)


def _arc_points(cx, cy, r, a0, a1, steps=60):
    pts = []
    for i in range(steps + 1):
        a = math.radians(a0 + (a1 - a0) * i / steps)
        pts.append((cx + r * math.cos(a), cy + r * math.sin(a)))
    return pts


def _draw_gauge(pdf, cx, cy, r, score, colour):
    thick = 6.5
    start = 135.0
    sweep = 270.0
    track_steps = 90
    pdf.set_draw_color(*LINE)
    pdf.set_line_width(thick)
    pts = _arc_points(cx, cy, r, start, start + sweep, track_steps)
    for i in range(len(pts) - 1):
        pdf.line(pts[i][0], pts[i][1], pts[i + 1][0], pts[i + 1][1])
    frac = max(0.0, min(1.0, score / 100.0))
    pdf.set_draw_color(*colour)
    pdf.set_line_width(thick)
    pts = _arc_points(cx, cy, r, start, start + sweep * frac, max(2, int(track_steps * frac)))
    for i in range(len(pts) - 1):
        pdf.line(pts[i][0], pts[i][1], pts[i + 1][0], pts[i + 1][1])
    pdf.set_xy(cx - r, cy - 6)
    pdf.set_font("Helvetica", "B", 26)
    pdf.set_text_color(*colour)
    pdf.cell(2 * r, 10, f"{score:.0f}", align="C", ln=2)
    pdf.set_xy(cx - r, cy + 4)
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(*MUTE)
    pdf.cell(2 * r, 4, "out of 100", align="C")
    # Reset stroke so later bordered boxes don't inherit the thick gauge line.
    pdf.set_line_width(0.3)
    pdf.set_draw_color(*LINE)


def _draw_prob_bars(pdf, x, y, w, probs, top_class, colour):
    label_w = 42.0
    val_w = 14.0
    track_w = w - label_w - val_w
    row_h = 9.0
    items = sorted(probs.items(), key=lambda kv: kv[1], reverse=True)
    cy = y
    for cls, prob in items:
        pct = prob * 100.0
        label = CLASS_LABELS.get(cls, cls.replace("_", " "))
        is_top = (cls == top_class)
        pdf.set_xy(x, cy)
        pdf.set_font("Helvetica", "B" if is_top else "", 9)
        pdf.set_text_color(*(INK if is_top else MUTE))
        pdf.cell(label_w, row_h, label, ln=0)
        tx = x + label_w
        ty = cy + row_h / 2 - 2.0
        pdf.set_fill_color(*LINE)
        pdf.rect(tx, ty, track_w, 4.0, style="F", round_corners=True, corner_radius=2)
        fill_w = max(0.6, track_w * (pct / 100.0))
        bar_col = colour if is_top else (148, 163, 184)
        pdf.set_fill_color(*bar_col)
        pdf.rect(tx, ty, fill_w, 4.0, style="F", round_corners=True, corner_radius=2)
        pdf.set_xy(tx + track_w + 2, cy)
        pdf.set_font("Helvetica", "B" if is_top else "", 9)
        pdf.set_text_color(*(INK if is_top else MUTE))
        pdf.cell(val_w, row_h, f"{pct:.1f}%", align="R", ln=0)
        cy += row_h
    return cy


def _chip(pdf, x, y, text, fill, text_col=WHITE, pad=3.0, h=6.5):
    pdf.set_font("Helvetica", "B", 8.5)
    w = pdf.get_string_width(text) + 2 * pad
    pdf.set_fill_color(*fill)
    pdf.rect(x, y, w, h, style="F", round_corners=True, corner_radius=1.6)
    pdf.set_xy(x, y)
    pdf.set_text_color(*text_col)
    pdf.cell(w, h, text, align="C")
    return w


def _ensure(pdf, needed):
    """Start a new page if `needed` mm won't fit before the bottom margin.
    (Sections are drawn with manual rect() calls, which don't auto-break.)"""
    if pdf.get_y() + needed > 297 - 16:
        pdf.add_page()


def generate_pdf(summary, session_id, output_path, gradcam_b64=None):
    if not _HAVE_FPDF:
        raise RuntimeError("fpdf2 not installed")

    disease = summary.get("disease", {})
    fatigue = summary.get("fatigue", {})
    ohi = summary.get("ohi", {})
    rec = summary.get("recommendation", {})
    symptoms = summary.get("symptoms_aggregate", 0.0)
    is_mock = disease.get("is_mock", True)

    ohi_score = float(ohi.get("ohi", 0.0))
    band = ohi.get("band", "Unknown")
    colour_key = ohi.get("colour", "green")
    band_col = BAND_COLOURS.get(colour_key, MUTE)

    probs = disease.get("probabilities", {})
    top_class = disease.get("top_class", "N/A")
    top_conf = float(disease.get("top_confidence", 0.0))

    pdf = _Report(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=16)
    pdf.set_title("Smart Eye - Ocular Health Report")
    pdf.add_page()

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*MUTE)
    now = datetime.now()
    pdf.cell(CONTENT_W / 2, 5, f"Session ID: {session_id}", ln=0)
    pdf.cell(CONTENT_W / 2, 5, f"Generated: {now.strftime('%d %b %Y, %H:%M')}", align="R", ln=1)
    pdf.ln(1.5)

    if is_mock:
        pdf.set_fill_color(255, 247, 224)
        pdf.set_draw_color(217, 145, 6)
        pdf.set_line_width(0.3)
        y0 = pdf.get_y()
        pdf.rect(MARGIN, y0, CONTENT_W, 8, style="DF", round_corners=True, corner_radius=1.5)
        pdf.set_xy(MARGIN + 3, y0)
        pdf.set_font("Helvetica", "B", 8.5)
        pdf.set_text_color(146, 97, 4)
        pdf.cell(0, 8, "MOCK MODEL ACTIVE  -  predictions are placeholders with no clinical meaning.", ln=1)
        pdf.ln(2)

    row_y = pdf.get_y()
    gauge_box_w = 60.0
    panel_x = MARGIN + gauge_box_w + 6
    panel_w = CONTENT_W - gauge_box_w - 6
    box_h = 46.0

    pdf.set_fill_color(*CARD)
    pdf.set_draw_color(*LINE)
    pdf.set_line_width(0.3)
    pdf.rect(MARGIN, row_y, gauge_box_w, box_h, style="DF", round_corners=True, corner_radius=2)
    pdf.set_xy(MARGIN, row_y + 3)
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(*MUTE)
    pdf.cell(gauge_box_w, 4, "OCULAR HEALTH INDEX", align="C", ln=1)
    _draw_gauge(pdf, MARGIN + gauge_box_w / 2, row_y + 26, 15.5, ohi_score, band_col)

    pdf.set_fill_color(*CARD)
    pdf.rect(panel_x, row_y, panel_w, box_h, style="DF", round_corners=True, corner_radius=2)
    pdf.set_xy(panel_x + 5, row_y + 5)
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(*MUTE)
    pdf.cell(0, 4, "RISK BAND", ln=1)
    _chip(pdf, panel_x + 5, row_y + 10, f"  {band.upper()}  ", band_col)
    pdf.set_xy(panel_x + 5, row_y + 21)
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(*MUTE)
    pdf.cell(0, 4, "TOP FINDING", ln=1)
    pdf.set_xy(panel_x + 5, row_y + 25.5)
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(*INK)
    pdf.cell(0, 7, CLASS_LABELS.get(top_class, top_class.replace("_", " ")), ln=1)
    pdf.set_xy(panel_x + 5, row_y + 33)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*MUTE)
    pdf.cell(0, 5, f"Model confidence: {top_conf * 100:.1f}%", ln=1)

    pdf.set_y(row_y + box_h + 6)

    _section_title(pdf, "Disease screening probabilities")
    by = pdf.get_y()
    end_y = _draw_prob_bars(pdf, MARGIN, by, CONTENT_W, probs, top_class, band_col)
    pdf.set_y(end_y + 4)

    if gradcam_b64:
        try:
            import base64, tempfile
            from PIL import Image as _PILImage
            _b64 = gradcam_b64.split(",", 1)[-1]
            _tmp = tempfile.NamedTemporaryFile(suffix=".png", delete=False)
            _tmp.write(base64.b64decode(_b64))
            _tmp.close()
            img_w = 46.0
            # Derive the on-page height from the image's real aspect ratio so
            # the following section never overlaps it.
            try:
                with _PILImage.open(_tmp.name) as _im:
                    iw, ih = _im.size
                img_h = img_w * (ih / iw) if iw else img_w
            except Exception:
                img_h = img_w
            _ensure(pdf, 9 + img_h + 6)
            _section_title(pdf, "Grad-CAM explainability")
            gy = pdf.get_y()
            pdf.image(_tmp.name, x=MARGIN, y=gy, w=img_w)
            pdf.set_xy(MARGIN + img_w + 6, gy + 2)
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(*MUTE)
            pdf.multi_cell(
                CONTENT_W - img_w - 6, 5,
                "Warm regions show where the model focused its attention when forming "
                "this prediction (ResNet branch). This is an explainability aid to support "
                "interpretation - it is not itself a diagnostic marker.",
            )
            pdf.set_y(max(gy + img_h, pdf.get_y()) + 5)
            os.unlink(_tmp.name)
        except Exception:
            pass

    _ensure(pdf, 60)
    _section_title(pdf, "Recommended actions")
    urgency = str(rec.get("urgency", "routine"))
    referral = bool(rec.get("referral_flag", False))
    actions = rec.get("actions", [])
    urg_col = {"routine": GREEN, "soon": AMBER, "urgent": RED}.get(urgency.lower(), MUTE)
    uy = pdf.get_y()
    xw = _chip(pdf, MARGIN, uy, f"  Urgency: {urgency.upper()}  ", urg_col)
    if referral:
        _chip(pdf, MARGIN + xw + 4, uy, "  Referral recommended  ", NAVY_2)
    pdf.set_y(uy + 10)
    if actions:
        ay = pdf.get_y()
        pdf.set_fill_color(*CARD)
        pdf.set_draw_color(*LINE)
        pdf.set_font("Helvetica", "", 9.5)
        line_h = 5.6
        est_h = 4 + len(actions) * line_h + 3
        pdf.rect(MARGIN, ay, CONTENT_W, est_h, style="DF", round_corners=True, corner_radius=2)
        pdf.set_xy(MARGIN + 4, ay + 3)
        for i, action in enumerate(actions, 1):
            pdf.set_x(MARGIN + 4)
            pdf.set_font("Helvetica", "B", 9.5)
            pdf.set_text_color(*BLUE)
            pdf.cell(5, line_h, f"{i}.", ln=0)
            pdf.set_font("Helvetica", "", 9.5)
            pdf.set_text_color(*INK)
            pdf.multi_cell(CONTENT_W - 12, line_h, str(action))
        pdf.set_y(ay + est_h + 5)

    _ensure(pdf, 44)
    _section_title(pdf, "Supporting signals")
    sy = pdf.get_y()
    col_w = (CONTENT_W - 6) / 2
    fcard_h = 30.0
    pdf.set_fill_color(*CARD)
    pdf.set_draw_color(*LINE)
    pdf.rect(MARGIN, sy, col_w, fcard_h, style="DF", round_corners=True, corner_radius=2)
    pdf.set_xy(MARGIN + 4, sy + 3)
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(*INK)
    pdf.cell(0, 5, "Fatigue monitoring", ln=1)
    fat_rows = [
        ("Blink rate", f"{fatigue.get('blink_rate_bpm', 0):.1f} bpm"),
        ("EAR", f"{fatigue.get('ear', 0):.3f}"),
        ("Fatigue score", f"{fatigue.get('fatigue_score', 0):.0f}/100"),
        ("Drowsy", "Yes" if fatigue.get("drowsy") else "No"),
    ]
    ry = sy + 9
    for k, v in fat_rows:
        pdf.set_xy(MARGIN + 4, ry)
        pdf.set_font("Helvetica", "", 8.5)
        pdf.set_text_color(*MUTE)
        pdf.cell(col_w / 2, 4.6, k, ln=0)
        pdf.set_font("Helvetica", "B", 8.5)
        pdf.set_text_color(*INK)
        pdf.cell(col_w / 2 - 6, 4.6, v, align="R", ln=1)
        ry += 4.8
    sx = MARGIN + col_w + 6
    pdf.set_fill_color(*CARD)
    pdf.rect(sx, sy, col_w, fcard_h, style="DF", round_corners=True, corner_radius=2)
    pdf.set_xy(sx + 4, sy + 3)
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(*INK)
    pdf.cell(0, 5, "Symptom survey", ln=1)
    pdf.set_xy(sx + 4, sy + 12)
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(*BLUE)
    pdf.cell(0, 9, f"{float(symptoms):.2f}", ln=1)
    pdf.set_xy(sx + 4, sy + 22)
    pdf.set_font("Helvetica", "", 8.5)
    pdf.set_text_color(*MUTE)
    pdf.cell(0, 4.5, "aggregate severity (1 none - 5 severe)", ln=1)
    pdf.set_y(sy + fcard_h + 6)

    _ensure(pdf, 16)
    dy = pdf.get_y()
    pdf.set_fill_color(254, 242, 242)
    pdf.set_draw_color(*RED)
    pdf.set_line_width(0.3)
    pdf.rect(MARGIN, dy, CONTENT_W, 12, style="DF", round_corners=True, corner_radius=2)
    pdf.set_xy(MARGIN + 4, dy + 1.5)
    pdf.set_font("Helvetica", "B", 8.5)
    pdf.set_text_color(*RED)
    pdf.cell(0, 4.5, "Important", ln=1)
    pdf.set_xy(MARGIN + 4, dy + 5.5)
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(120, 30, 30)
    pdf.multi_cell(
        CONTENT_W - 8, 3.6,
        "Smart Eye is a preliminary screening and triage support utility. It does NOT provide a "
        "clinical diagnosis. Final medical conclusions remain the responsibility of qualified "
        "healthcare professionals.",
    )

    os.makedirs(os.path.dirname(output_path) if os.path.dirname(output_path) else ".", exist_ok=True)
    pdf.output(output_path)
    return output_path


if __name__ == "__main__":
    sample = {
        "disease": {"probabilities": {"Normal": 0.15, "Cataract": 0.62, "Glaucoma": 0.18, "Diabetic_Retinopathy": 0.05},
                    "top_class": "Cataract", "top_confidence": 0.62, "is_mock": False, "model_id": "resnet-v1"},
        "fatigue": {"ear": 0.28, "blink_rate_bpm": 8.0, "drowsy": False, "fatigue_score": 42.0, "face_detected": True},
        "ohi": {"ohi": 62.0, "risk_index": 38.0, "band": "Moderate", "colour": "amber", "rule_activations": []},
        "recommendation": {"actions": ["Schedule an eye exam within 2 weeks.", "Reduce screen time and take regular breaks.", "Monitor symptoms and re-screen in one month."],
                           "urgency": "soon", "referral_flag": True, "disclaimer": "Not a clinical diagnosis."},
        "symptoms_aggregate": 2.75, "latency_ms": 312.0,
    }
    out = generate_pdf(sample, session_id=42, output_path="/tmp/test_report.pdf")
    print(f"PDF saved to: {out}")
